export const GET_BOOK ='GET_BOOK'
export const ADD_BOOK ='ADD_BOOKS'
export const BOOK_ERROR ='BOOK_ERROR'
export const USER_ERROR ='USER_ERROR'
export const GET_USER ='GET_USER'
export const LOGIN ='LOGIN'